### ISSUE TITLE
--haddock-arguments "-o haddock" behaviour varies depending on cache status

### ISSUE THREAD

**Issue by jmtd** [freckle/stack-action#27] opened 2023-08-15 14:34 UTC
at least I think it does.

I tried to specify stack arguments `--no-haddock-deps --haddock --haddock-arguments "-o haddock"` in order to generate haddock docs that I would publish as github pages in another step.

Initially this worked:
https://github.com/striot/striot/actions/runs/5867373079

But later on the "haddock" directory was mysteriously not present. 
https://github.com/striot/striot/actions/runs/5867892558
I _think_ this must be related to stack caching behaviour. But I really don't understand why. It seems the argument is passed through after a cache restore (lines 103-107):
https://github.com/striot/striot/actions/runs/5867892558/job/15909568042#step:4:107
```
Run stack --no-terminal --stack-yaml stack.yaml \
  stack --no-terminal --stack-yaml stack.yaml \
     \
    build --fast \
    --test --no-run-tests \
    --no-haddock-deps --haddock --haddock-arguments "-o haddock"
```

The test phase passes the same arguments. Could that delete the directory? shrug (lines 126+)

I added a couple of GHA steps to capture "find -ls" output
https://github.com/striot/striot/actions/runs/5868149343

This shows that

 * no haddock directory
 * haddock docs generated under ` ./.stack-work/install/.../...//doc/` despite `--no-haddock-deps` (or perhaps those were simply downloaded? I'm not sure)
 * no haddock docs for my local library, even under `.stack-work`
 
Any hints gratefully received. I'm relatively new to GHA debugging. TIA

**Comment by jmtd** [comment] 2023-08-15 14:58
Hmm. I'm wondering if, by passing `-o haddock`, I'm causing the Run with cache-miss to generate the docs successfully, but for them to not be cached (since there's nothing to tell stack-action to cache ./haddock as well); and on restore, stack believes there's no work to do when asked to build docs, since they were successfully built with the binaries pre-cache, but not restored in the Run with cache-hit.

I'll try not using `-o haddock` and instead putting a glob path into the actions/configure-pages@v3 step.

**Comment by pbrisbin** [comment] 2023-08-28 13:33
> since there's nothing to tell stack-action to cache ./haddock as well

This sounds right. Since you have to tell `actions/cache` what to cache _before_ it may exist, `stack-action` looks for packages (using presence of `package.yaml` or `*.cabal`) and then tells `actions/cache` to cache the usual `.stack-work` directories local to it. If you are putting artifacts anywhere else, they would not be cached. We could consider another option to specify extra cache paths, or you could use `actions/cache` yourself somehow, maybe.

What we do for this use-case is just build them to the default location, then use `${{ steps.stack.outputs.local-doc-root }}` (we set all `stack path` values as outputs) to get that location and then deploy (or move then deploy) them from there. Since this is under `.stack-work`, it is cached correctly.

**Comment by pbrisbin** [comment] 2024-02-12 13:56
Closing this as I believe it's not a bug of this action.

We cache all the usual `.stack-work` directories, so if you want something cached it should go in there. If you want to cache things outside of there, you should use `actions/cache` yourself.

If I've misunderstood something, feel free to re-open with more details.

**Closed by pbrisbin** 2024-02-12 13:56 UTC
